# (관리자)유저 목록&카운트
query SelectUsersByAdmin(
  $where: UserWhereInput
  $orderBy: [UserOrderByWithRelationInput!]
  $take: Int
  $skip: Int
  $cursor: UserWhereUniqueInput
) {
  selectUsersByAdmin(where: $where, orderBy: $orderBy, take: $take, skip: $skip, cursor: $cursor) {
    ...User
    phone
    joinedAt
    userPurchaseLog {
      id
      groupPurchaseList {
        id
        name
        description
        state
        startAt
        endAt
        createdAt
        isApplied
        image {
          original
        }
      }
    }
  }
  selectUsersCountByAdmin(where: $where)
}

# (관리자)유저 단일
query SelectUserByAdmin($userId: Int!) {
  selectUserByAdmin(userId: $userId) {
    ...User
    phone
    joinedAt
    userPurchaseLog {
      id
      groupPurchaseList {
        id
        name
        description
        state
        startAt
        endAt
        createdAt
        isApplied
        image {
          original
        }
      }
    }
  }
}
